### ISSUE TITLE
[FEATURE] Implement cards and boxes for signal tab using `bslib` functionality

### ISSUE THREAD

**Issue by jaemol** [United4Surveillance/signal-detection-tool#183]
**Is your feature request related to a problem? Please describe.**

As we have decided to use some of the functionality of the bslib-package, we want to start implementing it gradually.

**Describe the Solution You'd Like**

We want to utilize the cards and boxes functionality from the `bslib`-package for the (max three) stratification plots for the signal tab.

**Describe Alternatives**

Let it be as is. 

**Additional Context**

Not needed finished before General Assembly. 
Possible relation to #129 / #167.

**Comment by aj-thl** [comment]
Hi! 

I have done some testing with the bslib package (branch: feature/cards_and_boxes_using_bslib). In short, boxes are now implemented by using the bslib and, I have added cards feature for the max three stratification plots. However, to make everything work as intended, I was forced to change the shiny::fluidPage() with the bslib::page_fluid() in the app_ui.R. Another solution would be to stick with the shiny::fluidPage() and add bslib::bs_theme() but I think the layout would be basically the same. 

Anyway, I noticed that when bslib::page_fluid() is used the layout of the tabset titles is different when running the app in Rstudio. However, if one runs the app in web browser the layout of the tabset titles is quite same as they are in the current version of the app. I’m not entirely sure why this happens. I would guess that the viewer in Rstudio might not fully support all functionalities included in the bslib. You can see screenshots of both versions at the end of the post. 

It would be nice to hear your valuable thoughts and feedback before I proceed any further with this. I would especially appreciate if you could give feedback about the layout if you like or not. All suggestions for improvement are also very welcome! @tinneuro @tomasmartbert @alchalu @evolutionv2 

Tabset titles in the Rstudio: 
![image](https://github.com/United4Surveillance/signal-detection-tool/assets/141014269/615f987e-a1ec-4eac-b4b7-8bb2d83d17d9)

Tabset titles in the web browser: 
![image](https://github.com/United4Surveillance/signal-detection-tool/assets/141014269/7d09f291-6b40-4928-a358-06cb48415280)
