### ISSUE TITLE
[BUG] Legend in the map visualisation not fully correct

### ISSUE THREAD

**Issue by tinneuro** [United4Surveillance/signal-detection-tool#202]
**Describe the Bug**

![bug_map_plot](https://github.com/United4Surveillance/signal-detection-tool/assets/76201797/252a92af-5c7f-4371-8be1-7e7540a28465)
Somehow in the legend for the alarms in the map the "No alarms" has blue and white which is not so bad but the "At least 1 alarm" has a red and a blue line.

**To Reproduce**

1. load the test data into the appp
2. select county or community as stratum
3. look at the map in the signals tab

**Expected Behavior**

For "No alarms" it should be only a blue line
For "At least 1 alarm" it should be a red line

**Screenshots / Code Snippets (if applicable)**

If applicable, add screenshots, code snippets, or logs to help explain your problem.

**Environment (please complete the following information):**

- R version:
- Operating System:
- Package version (if applicable):

**Additional Context**

**Comment by tomasmartbert** [comment]
Note, it looks good in the html report! The signal tab and report ought to be synchronized(?)
