### ISSUE TITLE
[BUG] Incorrect display of timeseries plot when alarm was there

### ISSUE THREAD

**Issue by tinneuro** [United4Surveillance/signal-detection-tool#231]
**Describe the Bug**

When an alarm was in the timeseries it looks like the timeseries is extended to the future with 0 counts in the timeseries plot and also when clicking on the Signal Detection period the wrong period is shown.

**To Reproduce**

1. Upload the test data
2. Select age_group as strata and ears as algorithm. Leave everything else as default
3. Go to the signals tab and for the timeseries visualisation chose age_group and 25-29 (there was an alarm)
4. observe the inset below where one can select the period one wants to visualise. Extend it to the right.
5. Observe what happens when clicking onto Signal Detection Period

**Expected Behavior**

**Screenshots / Code Snippets (if applicable)**

If applicable, add screenshots, code snippets, or logs to help explain your problem.

**Environment (please complete the following information):**

- R version:
- Operating System:
- Package version (if applicable):

**Additional Context**

**Comment by tomasmartbert** [comment]
The original bug still seems to persist, but item 4 above how to reproduce has to be a little differenct:
When the time series plot displays at least one signal marker *, click on the "All time points" range selector button in the top left corner of the figure. Then the right end point of the total data date-range will be extended into the future.

**Comment by tomasmartbert** [comment]
I'm preparing a pull request together with some other issues in related places.
