### ISSUE TITLE
[FEATURE] Add caption to map

### ISSUE THREAD

**Issue by PvomFelde** [United4Surveillance/signal-detection-tool#301]
**Is your feature request related to a problem? Please describe.**

Caption for generated map in the signals tab is missing. If strata for e.g. "county" is selected, map is displayed without heading/caption underneath, while visualizations for other variables include caption stating e.g. "age group" or "sex".

**Describe the Solution You'd Like**

Add caption to map.

**Describe Alternatives**

**Additional Context**

**Comment by aj-thl** [comment]
This may be resolved by #305 where cards functionality is implemented for the max three strata plots and every plot should have they own caption including the maps.
