### ISSUE TITLE
[BUG] Current release signals tab not working when no stratification used 

### ISSUE THREAD

**Issue by tinneuro** [United4Surveillance/signal-detection-tool#303]
**Describe the Bug**

Error in the signals tab when no variable was used for stratification. 

**To Reproduce**

1. Upload our example data
2. Leave the input tab like it is
3. Look at the signals tab and observe the error in the console

**Expected Behavior**

**Screenshots / Code Snippets (if applicable)**

If applicable, add screenshots, code snippets, or logs to help explain your problem.

**Environment (please complete the following information):**

- R version:
- Operating System:
- Package version (if applicable):

**Additional Context**

**Comment by tomasmartbert** [comment]
I presume "Current release" refers to version 0.2.0? I'm not able to reproduce this error.
